format_version: 10
pipelines:
  fp_test_env_pipeline1:
    environment_variables:
      APPLY_WAIT: 1
      DATADOG_APP_KEY: asdasdas
    group: test
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      test_snuba:
        git: https://github.com/getsentry/test-snuba-k8s
        shallow_clone: true
        auto_update: true
        branch: main
    stages:
    - test1_env:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          run_script:
            timeout: 0
            tabs:
              Sample: my-artifact.html
            elastic_profile_id: snuba
            tasks:
            - script: |
                ./scripts/testenv.sh
            
