format_version: 10
pipelines:
  rgtest_pipeline1:
    environment_variables:
      TEST_VARIABLE: test1
    group: rgtest
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      test_snuba:
        git: https://github.com/getsentry/test-snuba-k8s
        shallow_clone: true
        auto_update: true
        branch: main
    stages:
    - rgtest_stage1:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          default_job:
            timeout: 0
            tabs:
              Sample: my-artifact.html
            elastic_profile_id: snuba
            tasks:
            - script: |
                echo $TEST_VARIABLE && export TEST_VARIABLE=test2 && echo $TEST_VARIABLE > ./test_variable.txt
            artifacts:
            - src: ./test_variable.txt
              dest: output
    - rgtest_stage2:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          default_job:
            timeout: 0
            tabs:
              Sample: my-artifact.html
            elastic_profile_id: snuba
            tasks:
            - fetchartifact:
                pipeline: rgtest_pipeline1
                stage: rgtest_stage1
                job: default_job
                srcfile: output/test_variable.txt
                dest: artifacts
            - script: |
               cat artifacts/test_variable.txt
