format_version: 10
pipelines:
  test_pipeline1:
    group: test
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      test_snuba:
        git: https://github.com/getsentry/test-snuba-k8s
        shallow_clone: true
        auto_update: true
        branch: main
    stages:
    - default_stage:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          default_job:
            timeout: 0
            tabs:
              Sample: my-artifact.html
            elastic_profile_id: snuba
            tasks:
            - script: |
                sleep 30
            - script: |
                ls -al /
            - exec:
                command: ./scripts/sayhi.sh
            - script: |
                /devinfra/scripts/gcloud/gcloud-wait.py
                gcloud container clusters get-credentials "$GKE_CLUSTER" --region "$GKE_REGION" --project "$GCP_PROJECT"
            - script: |
                kubectl get pods -n gocd
                kubectl get pods -n default
            - exec:
                command: /devinfra/scripts/k8s/k8s-deploy.py

