format_version: 10
pipelines:
  deploy-snuba-customer-1:
    display_order: 5
    environment_variables:
      SENTRY_REGION: customer-1
    group: snuba
    lock_behavior: unlockWhenFinished
    materials:
      deploy-snuba-us-pipeline-complete:
        pipeline: deploy-snuba-us
        stage: pipeline-complete
      test_snuba_k8s_repo:
        branch: main
        destination: snuba
        git: git@github.com:getsentry/test-snuba-k8s.git
        shallow_clone: false
    stages:
      - checks:
          jobs:
            checks:
              tasks:
                - script: |
                    ##!/bin/bash

                    echo "Check GitHub!"
      - deploy-primary:
          fetch_materials: true
          jobs:
            deploy-primary:
              environment_variables:
                LABEL_SELECTOR: service=snuba
              tasks:
                - script: |
                    ##!/bin/bash

                    eval $(regions-project-env-vars --region="${SENTRY_REGION}")

                    /devinfra/scripts/k8s/k8stunnel

                    k8s-deploy \
                      --label-selector="${LABEL_SELECTOR}" \
                      --image="us-central1-docker.pkg.dev/sentryio/snuba/image:${GO_REVISION_SNUBA_REPO}" \
                      --container-name="snuba" \
                      --container-name="snuba-admin"

                    k8s-deploy \
                      --label-selector="${LABEL_SELECTOR}" \
                      --image="us-central1-docker.pkg.dev/sentryio/snuba/image:${GO_REVISION_SNUBA_REPO}" \
                      --type="cronjob" \
                      --container-name="cleanup"
              timeout: 1200
      - pipeline-complete:
          jobs:
            pipeline-complete:
              tasks:
                - exec:
                    command: true
