format_version: 10
pipelines:
  deploy-snuba-us:
    display_order: 4
    environment_variables:
      SENTRY_REGION: us
    group: snuba
    lock_behavior: unlockWhenFinished
    materials:
      deploy-snuba-de-pipeline-complete:
        pipeline: deploy-snuba-de
        stage: pipeline-complete
      test_snuba_k8s_repo:
        branch: main
        destination: snuba
        git: git@github.com:getsentry/test-snuba-k8s.git
        shallow_clone: false
    stages:
      - checks:
          jobs:
            checks:
              elastic_profile_id: snuba
              tasks:
                - script: |
                    ##!/bin/bash

                    echo "Check GitHub!"
      - deploy-canary:
          fetch_materials: true
          jobs:
            deploy-canary:
              elastic_profile_id: snuba
              environment_variables:
                LABEL_SELECTOR: service=snuba,is_canary=true
              tasks:
                - script: |
                    ##!/bin/bash

                    eval $(/devinfra/scripts/regions/project_env_vars.py --region="${SENTRY_REGION}")

                    /devinfra/scripts/k8s/k8stunnel \
                    && /devinfra/scripts/k8s/k8s-deploy.py \
                      --label-selector="${LABEL_SELECTOR}" \
                      --image="us-central1-docker.pkg.dev/sentryio/snuba/image:${GO_REVISION_SNUBA_REPO}" \
                      --container-name="api" \
                      --container-name="consumer" \
                      --container-name="errors-consumer" \
                      --container-name="errors-replacer" \
                      --container-name="events-subscriptions-executor" \
                      --container-name="events-subscriptions-scheduler" \
                      --container-name="generic-metrics-counters-consumer" \
                      --container-name="generic-metrics-counters-subscriptions-executor" \
                      --container-name="generic-metrics-counters-subscriptions-scheduler" \
                      --container-name="generic-metrics-distributions-consumer" \
                      --container-name="generic-metrics-distributions-subscriptions-executor" \
                      --container-name="generic-metrics-distributions-subscriptions-scheduler" \
                      --container-name="generic-metrics-gauges-subscriptions-scheduler" \
                      --container-name="generic-metrics-gauges-subscriptions-executor" \
                      --container-name="generic-metrics-gauges-consumer" \
                      --container-name="generic-metrics-sets-consumer" \
                      --container-name="generic-metrics-sets-subscriptions-executor" \
                      --container-name="generic-metrics-sets-subscriptions-scheduler" \
                      --container-name="loadbalancer-outcomes-consumer" \
                      --container-name="metrics-consumer" \
                      --container-name="metrics-counters-subscriptions-scheduler" \
                      --container-name="metrics-sets-subscriptions-scheduler" \
                      --container-name="metrics-subscriptions-executor" \
                      --container-name="outcomes-billing-consumer" \
                      --container-name="outcomes-consumer" \
                      --container-name="profile-chunks-consumer" \
                      --container-name="profiles-consumer" \
                      --container-name="profiling-functions-consumer" \
                      --container-name="querylog-consumer" \
                      --container-name="replacer" \
                      --container-name="replays-consumer" \
                      --container-name="search-issues-consumer" \
                      --container-name="snuba-admin" \
                      --container-name="transactions-consumer-new" \
                      --container-name="transactions-subscriptions-executor" \
                      --container-name="transactions-subscriptions-scheduler" \
                      --container-name="spans-consumer" \
                      --container-name="rust-querylog-consumer" \
                      --container-name="rust-errors-consumer" \
                      --container-name="rust-metrics-consumer" \
                      --container-name="spans-exp-static-off" \
                      --container-name="dlq-consumer" \
                      --container-name="group-attributes-consumer" \
                      --container-name="metrics-summaries-consumer" \
                      --container-name="eap-spans-consumer" \
                      --container-name="eap-mutations-consumer" \
                      --container-name="eap-spans-profiled-consumer" \
                    && /devinfra/scripts/k8s/k8s-deploy.py \
                      --label-selector="${LABEL_SELECTOR}" \
                      --image="us-central1-docker.pkg.dev/sentryio/snuba/image:${GO_REVISION_SNUBA_REPO}" \
                      --type="cronjob" \
                      --container-name="cleanup" \
                      --container-name="optimize" \
                      --container-name="cardinality-report" \
                    && /devinfra/scripts/k8s/k8s-deploy.py \
                      --label-selector="${LABEL_SELECTOR}" \
                      --image="us-central1-docker.pkg.dev/sentryio/snuba/image:${GO_REVISION_SNUBA_REPO}" \
                      --type="statefulset" \
                      --container-name="spans-exp-static-on"
                - script: |
                    ##!/bin/bash

                    /devinfra/scripts/checks/datadog/monitor_status.py \
                      140973101


                    ## Above monitor IDs 140973101 map to following monitors:
                    ## Snuba API Health Check is Failing
              timeout: 1200
      - deploy-primary:
          fetch_materials: true
          jobs:
            deploy-primary:
              elastic_profile_id: snuba
              environment_variables:
                LABEL_SELECTOR: service=snuba
              tasks:
                - script: |
                    ##!/bin/bash

                    eval $(/devinfra/scripts/regions/project_env_vars.py --region="${SENTRY_REGION}")

                    /devinfra/scripts/k8s/k8stunnel \
                    && /devinfra/scripts/k8s/k8s-deploy.py \
                      --label-selector="${LABEL_SELECTOR}" \
                      --image="us-central1-docker.pkg.dev/sentryio/snuba/image:${GO_REVISION_SNUBA_REPO}" \
                      --container-name="api" \
                      --container-name="consumer" \
                      --container-name="errors-consumer" \
                      --container-name="errors-replacer" \
                      --container-name="events-subscriptions-executor" \
                      --container-name="events-subscriptions-scheduler" \
                      --container-name="generic-metrics-counters-consumer" \
                      --container-name="generic-metrics-counters-subscriptions-executor" \
                      --container-name="generic-metrics-counters-subscriptions-scheduler" \
                      --container-name="generic-metrics-distributions-consumer" \
                      --container-name="generic-metrics-distributions-subscriptions-executor" \
                      --container-name="generic-metrics-distributions-subscriptions-scheduler" \
                      --container-name="generic-metrics-gauges-subscriptions-scheduler" \
                      --container-name="generic-metrics-gauges-subscriptions-executor" \
                      --container-name="generic-metrics-gauges-consumer" \
                      --container-name="generic-metrics-sets-consumer" \
                      --container-name="generic-metrics-sets-subscriptions-executor" \
                      --container-name="generic-metrics-sets-subscriptions-scheduler" \
                      --container-name="loadbalancer-outcomes-consumer" \
                      --container-name="metrics-consumer" \
                      --container-name="metrics-counters-subscriptions-scheduler" \
                      --container-name="metrics-sets-subscriptions-scheduler" \
                      --container-name="metrics-subscriptions-executor" \
                      --container-name="outcomes-billing-consumer" \
                      --container-name="outcomes-consumer" \
                      --container-name="profile-chunks-consumer" \
                      --container-name="profiles-consumer" \
                      --container-name="profiling-functions-consumer" \
                      --container-name="querylog-consumer" \
                      --container-name="replacer" \
                      --container-name="replays-consumer" \
                      --container-name="search-issues-consumer" \
                      --container-name="snuba-admin" \
                      --container-name="transactions-consumer-new" \
                      --container-name="transactions-subscriptions-executor" \
                      --container-name="transactions-subscriptions-scheduler" \
                      --container-name="spans-consumer" \
                      --container-name="rust-querylog-consumer" \
                      --container-name="rust-errors-consumer" \
                      --container-name="rust-metrics-consumer" \
                      --container-name="spans-exp-static-off" \
                      --container-name="dlq-consumer" \
                      --container-name="group-attributes-consumer" \
                      --container-name="metrics-summaries-consumer" \
                      --container-name="eap-spans-consumer" \
                      --container-name="eap-mutations-consumer" \
                      --container-name="eap-spans-profiled-consumer" \
                    && /devinfra/scripts/k8s/k8s-deploy.py \
                      --label-selector="${LABEL_SELECTOR}" \
                      --image="us-central1-docker.pkg.dev/sentryio/snuba/image:${GO_REVISION_SNUBA_REPO}" \
                      --type="cronjob" \
                      --container-name="cleanup" \
                      --container-name="optimize" \
                      --container-name="cardinality-report" \
                    && /devinfra/scripts/k8s/k8s-deploy.py \
                      --label-selector="${LABEL_SELECTOR}" \
                      --image="us-central1-docker.pkg.dev/sentryio/snuba/image:${GO_REVISION_SNUBA_REPO}" \
                      --type="statefulset" \
                      --container-name="spans-exp-static-on"
              timeout: 1200
      - health_check:
          jobs:
            health_check:
              elastic_profile_id: snuba
              environment_variables:
                LABEL_SELECTOR: service=snuba
              tasks:
                - script: |
                    ##!/bin/bash

                    echo "SaaS Sentry Health Check!"
                - script: |
                    ##!/bin/bash

                    echo "SaaS Sentry Error Check!"
                - script: |
                    ##!/bin/bash

                    echo "SaaS DDOG Health Check!"


                    ## Above monitor IDs map to following monitors respectively:
                    ## Snuba - SLO - High API error rate
                    ## Snuba - Too many restarts on Snuba pods
      - pipeline-complete:
          jobs:
            pipeline-complete:
              tasks:
                - exec:
                    command: true
