apiVersion: v1
kind: ServiceAccount
metadata:
  name: snuba-admin
  namespace: {{.Release.Namespace}}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: snuba-admin
  name: snuba-admin
  namespace: {{.Release.Namespace}}
spec:
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    service: snuba-admin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app_feature: infra
    app_function: mixed
    cogs_category: shared
    component: admin
    environment: production
    is_canary: "false"
    service: snuba
    system: admin
  name: snuba-admin-production
  namespace: {{.Release.Namespace}}
spec:
  minReadySeconds: 5
  replicas: 1
  selector:
    matchLabels:
      service: snuba-admin
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        configVersion: 1b6513a9eaebcd3a0cd7523829ea7cdb
      labels:
        service: snuba-admin
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: service
                    operator: In
                    values:
                      - snuba-admin
              topologyKey: kubernetes.io/hostname
      containers:
        - args:
            - admin
            - --processes=3
            - --threads=4
          env:
            - name: SNUBA_SETTINGS
              value: /etc/snuba.conf.py
            - name: SENTRY_ENVIRONMENT
              value: st-mystuff
            - name: UWSGI_MAX_REQUESTS
              value: "10000"
            - name: UWSGI_DISABLE_LOGGING
              value: "true"
            - name: UWSGI_ENABLE_THREADS
              value: "true"
            - name: UWSGI_DIE_ON_TERM
              value: "true"
            - name: UWSGI_NEED_APP
              value: "true"
            - name: UWSGI_HTTP_SOCKET
              value: 0.0.0.0:8000
            - name: UWSGI_IGNORE_SIGPIPE
              value: "true"
            - name: UWSGI_IGNORE_WRITE_ERRORS
              value: "true"
            - name: UWSGI_DISABLE_WRITE_EXCEPTION
              value: "true"
            - name: ENVOY_ADMIN_PORT
              value: "15000"
            - name: SNUBA_PROFILES_SAMPLE_RATE
              value: "1.0"
            - name: CLICKHOUSE_MIGRATIONS_USER
              value: snuba
          image: us.gcr.io/sentryio/snuba:92816dfc25a17de2dccd3df68a86d8de2871bfc8
          lifecycle:
            preStop:
              exec:
                command:
                  - /bin/sh
                  - -ec
                  - touch /tmp/snuba.down && sleep 40
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
          name: snuba-admin
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5
          resources:
            limits:
              memory: 512Mi
            requests:
              cpu: 500m
              memory: 512Mi
          startupProbe:
            failureThreshold: 12
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
          volumeMounts:
            - mountPath: /etc/snuba.conf.py
              name: snuba-config
              readOnly: true
              subPath: snuba.conf.py
            - mountPath: /dev/shm
              name: dshm
      serviceAccount: snuba-admin
      serviceAccountName: snuba-admin
      terminationGracePeriodSeconds: 40
      volumes:
        - configMap:
            items:
              - key: snuba.conf.py
                path: snuba.conf.py
            name: snuba
          name: snuba-config
        - emptyDir:
            medium: Memory
          name: dshm
        - emptyDir: {}
          name: envoy-bootstrap-data
